import { StyleSheet } from 'react-native';
import { COLORS, FONTS, RADIUS, SHADOWS, SPACING } from '../../constants/theme';

export const AUTH_COMPACT_HEIGHT = 740;

export const authStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: COLORS.background },
  blobTop: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(82, 183, 136, 0.18)',
  },
  blobBottom: {
    position: 'absolute',
    bottom: 120,
    left: -90,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(27, 67, 50, 0.08)',
  },
  container: { paddingHorizontal: SPACING.lg },
  containerCompact: { paddingHorizontal: SPACING.md },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.xl,
    padding: SPACING.lg,
    borderWidth: 1,
    borderColor: 'rgba(27, 67, 50, 0.06)',
    ...SHADOWS.lg,
  },
  cardCompact: {
    padding: SPACING.md,
    borderRadius: RADIUS.lg,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.text,
    marginBottom: 4,
  },
  cardTitleCompact: { fontSize: 16, marginBottom: 2 },
  cardHint: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: SPACING.md,
    lineHeight: 18,
  },
  cardHintCompact: {
    fontSize: 12,
    marginBottom: SPACING.sm,
    lineHeight: 16,
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.lg,
    padding: 4,
    marginBottom: SPACING.md,
  },
  tabsCompact: { marginBottom: SPACING.sm, padding: 3 },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: SPACING.sm + 2,
    borderRadius: RADIUS.md,
  },
  tabCompact: { paddingVertical: SPACING.sm, gap: 4 },
  tabActive: {
    backgroundColor: COLORS.surface,
    ...SHADOWS.sm,
  },
  tabText: { fontSize: 14, fontWeight: '700', color: COLORS.textMuted },
  tabTextCompact: { fontSize: 13 },
  tabTextActive: { color: COLORS.primary },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginVertical: SPACING.md,
  },
  dividerCompact: { marginVertical: SPACING.sm },
  dividerLine: { flex: 1, height: 1, backgroundColor: COLORS.border },
  dividerText: { fontSize: 12, color: COLORS.textMuted, fontWeight: '600' },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginTop: SPACING.lg,
    paddingVertical: SPACING.xs,
  },
  footerCompact: { marginTop: SPACING.sm },
  footerText: { fontSize: FONTS.minSize, color: COLORS.textSecondary },
  link: { fontSize: FONTS.minSize, color: COLORS.primary, fontWeight: '800' },
  benefitRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: SPACING.sm,
    marginTop: SPACING.md,
  },
  benefitRowCompact: { marginTop: SPACING.sm, gap: 6 },
  benefitChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: 7,
    borderRadius: RADIUS.full,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOWS.sm,
  },
  benefitChipCompact: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: 4,
  },
  benefitText: { fontSize: 12, fontWeight: '700', color: COLORS.primary },
  benefitTextCompact: { fontSize: 11 },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: SPACING.md,
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  backBtnCompact: { marginBottom: SPACING.sm },
  backText: { fontSize: 15, fontWeight: '700', color: COLORS.primary },
});
